greenpeace/planet4-builder

src/Makefile, src/ls.sh, src/modify_users.sh, src/run_bash_script_in_php_pod.sh
Non tested, and very possibly breaking everything. Includes: 
- A meta script run_bash_script_in_php_pod.sh allowing us to run other bash scripts in the kubernetes pod php of given deploy
- A test bash script ls.sh  that just lists the current directory (so that we can test if the metascript works)
- A wp script modify_users.sh that adds missing users to a deployed wp installation (not used yet)
- A modification in the Makefile where we try to run the script ls.sh after a deploy.
=> Script to add missing users to all deployed p4 websites

src/flush_redis.sh
Doing it against the master, because the current develop was failing. 
The fix does not break the deployments. I run the :
https://circleci.com/workflow-run/568b6995-eeb2-4f9d-9a0f-1cf30a920b80
(and the follow up autodeployments) with gcr.io/planet-4-151612/p4-builder:build-209 which was build with this branch. 
The sync job also run without problems: 
https://circleci.com/workflow-run/376858ca-48ff-4039-8053-46cc71f84045
=> Make the flush_redis able to run from anywhere

src/Makefile
We don't need this at this time, as all users we need are in all environments.
=> Commenting out add users script

src/Makefile, src/checkout.sh, src/rewrite_app_repos.sh
Two changes. (Name of branch implies only one)
1) If a variable named `MASTER_THEME_BRANCH` exists when builder's `make` is called, these changes replace the tag/branch in composer.json with the given one. Like that we can change the master-theme on the fly while building, and we can do testing on specific branches. (Similar work will follow for other plugins)
2) Fixed an error with checkout.sh: Even though in `make` the checkout was being called as: 
```
checkout:
GIT_SOURCE=$(GIT_SOURCE) \
GIT_REF=$(GIT_REF) \
MERGE_SOURCE=$(MERGE_SOURCE) \
MERGE_REF=$(MERGE_REF) \
./checkout.sh
```
The last two parameters (MERGE_SOURCE and MERGE_REF) where not being taken into account. Fixed that.
=> Rewrite master theme branches and fix checkout merge params

src/Makefile, src/build/Dockerfile.in, src/docker-compose.yml, src/helm_deploy.sh, src/openresty/Dockerfile.in, src/rewrite_dockerfiles.sh
Enables building the application image from an arbitrary parent.
Defaults to, but no longer hard-coded to `gcr.io/planet-4-151612/wordpress`
Configure via NRO `.circleci/config.yml` PARENT_IMAGE environment variable.
Tested in
- https://circleci.com/gh/greenpeace/planet4-flibble/1817
- https://circleci.com/gh/greenpeace/planet4-flibble/1819
=> Support building application images from different parents.

src/Makefile, src/bake.sh, src/checkout.sh, src/run_post_deploy_scripts.sh
Check if base-fork post-deploy scripts are persisted from previous job, before cloning base-fork repo
You can check it out in this ci [build](https://circleci.com/gh/greenpeace/planet4-koyansync/538)
In conjuction with changes done in [koyan-sync](https://github.com/greenpeace/planet4-koyansync/commit/b514ccfdd43d48c954d387141ed477e05d9bf4eb).
=> PLANET-3163 Rationalise post deploy scripts

src/Makefile
PLANET-3532 . Use the release branch of the planet4-base-fork for staging sites, the develop branch for develop sites and the master branch for production sites. 
This will modify the release process, since after this gets merged and deployed, when we do a release to production we will have to be aware which branch of planet4-base-fork we are pushing, and what they have inside them.
An example can be seen in the koyansync website. Checking circleCI, the last 3 successful builds/deploys (of develop, staging, production sites respectively) used the relevant planet4-base-fork branches
Check them out by looking at the build job -> step called "Make", the GIT_REF variable.
Also can be seen at the p4-dev report of the koyansync develop and staging sites
=> USE release branches in staging sites

src/notify-sync-admins.sh
This script sends a predefined email when invoked to the admin of a wordpress website, notifying them that two days later the sync script will be called.
The script will be called with related changes in the circleCI configuration
=> PLANET-3915 Adding a script that notifies website admin about the sync

src/build/Dockerfile.in, src/rewrite_app_repos.sh
* Get github repository, build assets, and put all built assets in a
directory in the source directory for all plugins that have their
dev version passed using a branch name. That directory has the same
structure as the source directory.
* Use rsync to apply that directory like a patch.
* Add environment variables for newer plugins so that these are also
tested.
=> PLANET-4427 Make builder build assets for dev branches

src/rewrite_app_repos.sh
This is a temporary fix. We should build assets once.
=> Add a check for pending parallel jobs before building assets

src/rewrite_app_repos.sh
* Sed expected a space between the package name and the colon, however
this space is not there for some of the repos. The result was that sed
didn't replace anything, causing further jobs to not have the intended
version of the plugins. This fixes the issue for now, however depending
on regex substitution is error prone so we should do this in a more
robust way.
=> PLANET-5192 Ensure sed matches regardless of space

src/rewrite_app_repos.sh
Provide the pid of each `build_assets` subprocess to `wait`. If one fails the script will also fail
=> PLANET-5407 Fail script when build_assets fails

src/rewrite_app_repos.sh
`node` (and `npm`) have a default 512M memory limit in most environments. Doubling this limit to overcome often ENOMEM errors we get on build, probably due to constantly increasing our js codebase.
Here is a failed example (search for `ENOMEM`):
https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/2322/workflows/d4b99ff0-bb37-4969-9cbc-848fa5478415/jobs/6137
Here is a successful example with this change (search for `NODE_OPTIONS` inside the `Build containers` job):
https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/2324/workflows/706bb51d-3cc9-498b-b327-48084fc233db/jobs/6144
=> PLANET-5407 Incease node memory limit

.editorconfig, .githooks/pre-commit, Makefile, README.md, src/activate_plugins.sh, src/backup_db.sh, src/bake.sh, src/checkout.sh, src/configure_redis.sh, src/flush_redis.sh, src/helm_confirm.sh, src/helm_deploy.sh, src/helm_prepare.sh, src/helm_rollback.sh, src/lib/retry.sh, src/newrelic_deployment.sh, src/notify-sync-admins.sh, src/rewrite_app_repos.sh, src/rewrite_dockerfiles.sh, src/run_bash_script_in_php_pod.sh, src/run_post_deploy_scripts.sh, src/sql_create_sync_file.sh, src/sql_to_sync_site.sh, src/sync_to_test_site.sh, src/use_release_branches.sh
This adds shfmt to the shellscript linting and all scrips in this repo have been auto-formatted.
I have added a `format` and `format-sh` target to the Makefile. Do we want to keep this?
Other than that I also used `shfmt -f .` to find files for `ShellCheck` since it can find files both based on filename and shebang (which now also includes the `.githooks/pre-commit` file in this repo).
Fixes greenpeace/planet4#72
=> Planet 5322 add shfmt

src/get-fork-pr-branch.sh, src/rewrite_app_repos.sh
* Use jq instead of sed to handle substitution in json.
* If the a fork user was passed, add the fork repository to the
repositories. Else jobs running for a PR in a fork are not able to get
the code.
=> PLANET-5221 use jq and support fork PRs

src/rewrite_app_repos.sh
Also decreases npm mem limit to a more sane value. 2G of RAM actually trigger more failures, because of two processes running at the same time in a 4G instance.
Tested here, where npm fails but re-tries:
https://app.circleci.com/pipelines/github/greenpeace/planet4-cidev/341/workflows/7399bcab-0caf-4804-84aa-8525ccaf4321/jobs/960
(hint: search for `build attempt`)
=> Retry npm build on failure

src/rewrite_app_repos.sh
Running npm/node in parallel turned out to be highly unreliable, so in the end jobs take more time.
- Reduce verbosity (set).
- Increase mem limit since now it's one process running.
=> Build assets in sequence again

src/Makefile
Split deploy target into three (prepare, deploy, post), so these can be re-used for rollback.
Rollback also checkouts code in order to run post-deploy scripts.
=> PLANET-5443 Add rollback target to Makefile

src/build/Dockerfile.in, src/rewrite_app_repos.sh
Ref: https://jira.greenpeace.org/browse/PLANET-5484
Don't build assets if we're on a tag. These will have a zip uploaded to the corresponding github release, which will be used by composer instead of the default files because we added a dependency on https://github.com/greenpeace/github-archive-installer.
In order to make that plugin work on the test instance I needed to modify the composer install and update commands. I couldn't find a reason why we would actually need to run composer 4 times, it's working by running only the last one. But I need to further investigate if this really produces the same behavior as before, as I guess there is a reason why it was run 4 times. EDIT: I kept the composer commands the way they were (except splitting them into multiple `RUN` commands). It turned …
=> Planet 5484 don't build assets for tags

src/rewrite_app_repos.sh
[This check](https://github.com/greenpeace/planet4-builder/compare/better-asset-build-output?expand=1#diff-977f550fdc3a10875108491b359854ecbe7bbc2301dcaf0688f3f1b7d9e3dc40L117) was behaving incorrectly for dev sites: the branches defined in base-fork were not being built because the 2 variables that were being compared were both emptied if any subsequent file didn't require the repository.
Instead I moved the check to the loop, so that `$repo_branch` only exists if the last occurrence of the repository is a branch. If a branch is encountered, but a subsequent file has a tag, it will empty the variable to prevent building the branch.
I also flattened the structure a bit to make it more readable, and added some additional logging.
=> Fix assets not building for dev sites

src/Makefile
Done a little differently than for the wordpress image, as there is already an rsync before the build, so we can do the rsync here to already put the built assets in place before the docker build.
Example build: https://app.circleci.com/pipelines/github/greenpeace/planet4-test-janus/12/workflows/dcb5c6ee-313b-4a7a-bdb8-2a06378e2849/jobs/51
=> rsync the built files too before building openresty

src/book-test-instance.py
This script triggers a booking process to reserve a test instance for a given pull request.
```
usage: book-test-instance.py [-h] [--pr-url PR_URL] [-n] [-v] [--no-cache] [--no-booking] [--results RESULTS]
optional arguments:
-h, --help         show this help message and exit
--pr-url PR_URL    pull request URL
-n, --dryrun       gives a course of action but doesn't execute
-v, --verbosity    increase output verbosity
--no-cache         disable request cache use
--results RESULTS  save result in json to the specified file (default booking-results.json)
```
It uses CircleCI environment variable `CIRCLE_PULL_REQUEST` by default.  
Recommended usage in CircleCI is something like 
```
book-test-instance.py -v
instance=$(jq 'if .instance == false then "" else .instance end' …
```
=> Add booking script, used to book a test instance

src/trigger_test_instance.sh
This should clean up the repo definition and reset to `dev-master` if that is provided as an argument to the script.
=> Use target branch if i'ts a merge commit

src/book-test-instance.py
[This error](
https://app.circleci.com/pipelines/github/greenpeace/planet4-master-theme/2599/workflows/9e96e88e-0c0e-4e59-96b6-6c31d19aa537/jobs/13300) happens when trying to write in logs an object Response 204
```
Traceback (most recent call last):
File "/home/circleci/book-test-instance.py", line 406, in <module>
}, results_file)
File "/home/circleci/book-test-instance.py", line 327, in save_results
json.dump(results, results_file, indent=2)
File "/usr/lib/python2.7/json/__init__.py", line 189, in dump
for chunk in iterable:
File "/usr/lib/python2.7/json/encoder.py", line 434, in _iterencode
for chunk in _iterencode_dict(o, _current_indent_level):
File "/usr/lib/python2.7/json/encoder.py", line 408, in _iterencode_dict
for chunk in chunks:
File "/usr/lib/python2.7/json/encoder.py", …
```
=> Fix serialize error at log dump

Makefile, src/bin/book-test-instance.py, src/bin/composer-requirements.py
Ref: https://jira.greenpeace.org/browse/PLANET-5946
---
Besides overriding existing dependencies, we could have a requirement we only want on one environment.
This has also an extra commit that uses `flake8` to have some basic (pep8) linting on python scripts. And fixed the existing issues.
=> PLANET-5946 Add also extra environment requirements

src/bin/book-test-instance.py
This was still using `develop` but we switched all to use `main` as primary branch.
=> Test instances now use main

src/Makefile, src/bin/checkout.sh, src/bin/composer-requirements.py, src/bin/rewrite_dockerfiles.sh
Ref: https://jira.greenpeace.org/browse/PLANET-5946
---
Adjusted the composer script to be more generic. Instead of looking for `composer-local.json` we can can pass the full file
path as an argument. This way we can use the script for base repository requirements also.
---
Simplified Makefile scripts to use the latest tag when doing a production release (instead of master) and main branch when on
development (instead of develop). And also preparation for renaming the base repo, removing the fork suffix.
=> PLANET-5946 Adjust scripts for single branch base repo

src/bin/rewrite_app_repos.sh
It's [hidden in the docs](https://git-scm.com/docs/git-submodule#Documentation/git-submodule.txt---branchltbranchgt), but the `--remote` flag made it use the HEAD of the remote branch instead of the actual commit included in the current commit of the parent repo. Noticed it when the [paths changed here and it failed the assets build](https://app.circleci.com/pipelines/github/greenpeace/planet4-plugin-gutenberg-blocks/4065/workflows/8ea583ce-5434-4691-bbef-d63965916fbe/jobs/14386), while the assets build in the zip job of the same workflow did pass.
We probably didn't notice all this time because, except for acceptance tests, most workflows don't use branch versions so they don't have to build the assets.
=> Remove --remote option

src/bin/rewrite_app_repos.sh, src/build/Dockerfile.in
Ref: https://jira.greenpeace.org/browse/PLANET-6020
---
Two things changed here:
1. Removed `composer install` steps, since we have `composer update` in place. The base repo doesn't have a lock file, so I adjusted the update commands accordingly. This was fine with composer 1 but it breaks on 2.
2. Removed the check on whether we already are in a repo checkout. This was what it was breaking last time, complaining of folder being empty. Not sure why, but we can research that later if we want. It only costs us a few seconds to re-clone the repo.
=> PLANET-6020 Upgrade to composer 2

src/bin/checkout.sh, src/bin/rewrite_app_repos.sh
Since we already detect tags at this step, besides skipping building the assets, we can also fetch the zip file from Github release already. We can then use [composer's artifact](https://getcomposer.org/doc/05-repositories.md#artifact) repository type in the next step to just install that zip from the local filesystem.
The only caveat of using artifacts is that `composer.json` file in that zip needs to have the proper version. To achieve that, we inject the version when we create the zip (see [https7c790e110b471e510de07e1d7218b96055440407](https://github.com/greenpeace/planet4-plugin-gutenberg-blocks/commit/7c790e110b471e510de07e1d7218b96055440407).
We need also to make sure test instances work with this, where we already use a different repository type (package). Since we use the version …
=> Fetch zip file for tags to use composer's artifact type

src/bin/composer-requirements.py
This is to catch an edge case where we do have an environment specific json file, but it's missing the require array.
=> Ignore env file when requirements are missing

src/docker-compose.yml
If `WP_VERSION` is not defined as an env variable then leave it blank. This will allow us to fallback on the bare repo `wp-version` definition.
=> Remove WP_VERSION fallback value

.editorconfig, src/bin/composer-requirements.py
Ref: https://jira.greenpeace.org/browse/PLANET-6307
---
Additionally to merging composer requirements, the same script can also
merge `wp-version`. Same as before It works for both base and nro level
composer and environment files.
=> PLANET-6307 Adjust composer merge script to account for wp-version

src/bin/sync_to_test_site.sh
Cf https://github.com/greenpeace/planet4-master-theme/pull/1527
Using a custom command for orphan posts update, to reduce execution time.
Sync from international:
- Before fix, 40 minutes https://app.circleci.com/pipelines/github/greenpeace/planet4-test-pandora/152/workflows/4096c607-bc6c-48b7-bda8-aa84c5ee3ed9/jobs/773
- After fix, 4 minutes https://app.circleci.com/pipelines/github/greenpeace/planet4-test-umbriel/70/workflows/98091edc-57fa-43d5-ad86-127811a02134/jobs/406
=> Faster update command for data sync to test instances

src/bin/helm_rollback.sh
Currently the rollback script only looks for `SUPERSEDED` revisions, which in cases of failed deployments will skip the last successfully deployed and go to the one before that.
Even in cases where the last revision is successfully deployed, but we do want to rollback, this still works since we use: `previous=${2:-$((current - 1))}` right before the look up loop.
=> Use DEPLOYED revisions also for rollback

src/Makefile
This update requires that https://github.com/greenpeace/planet4-helm-wordpress/pull/18 is merged and version 0.8.20 is tagged first. 
Then do the following:
1) Merge
2) Trigger dev redeployment - monitor
3) Rerun latest prod deployment - monitor
=> Update helm chart to 0.8.20

src/Makefile, src/var/values.yaml.in
* CloudSQL is now deployed centrally so this portion is unneeded
* Traefik is being phased out - in the latest version of the chart this stanza is also not used
=> Remove unused components of values file

src/bin/check-data-sync-flag.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6772
---
Added a `|| true` in the end since an empty option returns a failed exit status. It's more reliable to actually look for an `on` value on that flag.
I used cidev to test this.
1. Changed the [builder tag](https://github.com/greenpeace/planet4-cidev/blob/af2743c9f24db22aebf2f244679f3404b286bdab/.circleci/config.yml#L15)  to use this branch.
2. Added this extra script on [sync-to-develop job](https://github.com/greenpeace/planet4-cidev/blob/af2743c9f24db22aebf2f244679f3404b286bdab/.circleci/config.yml#L422-L424).
3. I amended the [data sync workflow](https://github.com/greenpeace/planet4-cidev/blob/af2743c9f24db22aebf2f244679f3404b286bdab/.circleci/config.yml#L549-L569) to run for every commit on `main` branch.
Then I tested by …
=> Add script to check data sync flag

src/bin/backup_db.sh
Fixes issue raised by flo in the backup script on the builder image. The namespace was not being fetched properly so just required a small modification to the script to properly support helm3.
=> fix: backup script was not fetching namespace properly

src/bin/sql_create_sync_file.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6841
I modified the export script in two different phases, and used a test instance to verify the dump. The regular `--ignore-tables` flag is being used, but unfortunately `mysqldump` doesn't support wildcards.
1. Full backup (same as the current script)
- [Pipeline](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-venus/353/workflows/72617024-97b9-43f4-9e29-1a5e4462293b/jobs/2051/steps)
- On "Export DB" job the tables are listed in the `mysqldump` output.
- In Artifacts the db dump can be downloaded and inspected with an editor that can handle big files (eg. vim 😁)
2. Back ignoring GF tables
- [Pipeline](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-venus/354/workflows/bcd32269-1b4f-4482-8e60-2834f3ea7b28/ …
=> PLANET-6841 Exclude GF database tables from sync script

src/bin/sql_create_sync_file.sh, src/bin/sql_to_sync_site.sh
Ref: https://jira.greenpeace.org/browse/PLANET-6854
Uses: https://github.com/greenpeace/planet4-master-theme/pull/1777
Gravity forms addons have predictable settings option name, so we could remove those settings as shown [in the first commit](https://github.com/greenpeace/planet4-builder/commit/bf539e4a94b6c9e55d3bb11734ff879e5c3f7887)
```console
> wp option delete $(wp option list --search='gravityformsaddon_*_settings' --field=option_name)
```
but that might  remove more settings than necessary, as some settings only specify what is enabled or not.
The option taken here is to create a disconnect command in master-theme `wp p4-gf-addons disconnect` (easier to maintain) and use it here in the context of development/staging
=> PLANET-6854: Disconnect Gravity Forms from external integrations on staging/dev sites

src/bin/configure_redis.sh, src/bin/flush_redis.sh
The latest version of the redis helm chart changes the labels that are applied to the statefulset pods. This commit updates the label selectors.
=> fix: update flush script

src/Makefile
This PR bumps the p4/wordpress helm chart. 
All sites will need to have the redis caching statefulset deleted and then allow the helm release to recreate it. This will not cause any outage because they are just used for caching and the sites work fine without them.
Process:
1. Merge this PR
2. Delete all dev statefulset
3. Run dev sites release
4. Delete all prod statefulsets
5. Run prod sites release
=> fix: bump helm chart

src/bin/helm_deploy.sh
This is some setup for moving the namespaces around in dev and staging. This was the default behaviour with Helm2 that was disabled with Helm3. Adding this command line switch re-enables it.
=> fix: enable namespace creation if ns doesn't exist

src/Makefile, src/bin/reset_test_instance.sh
Imports latest defaultcontent DB dump and syncs stateless bucket. This runs on `make reset` that only existis in test instances pipelines. We can use that the reset-instance job in app repos when we switch app branches back to `dev-main`.
This is [an example](https://app.circleci.com/pipelines/github/greenpeace/planet4-test-umbriel/230/workflows/5a8bfd4d-ee71-4d1f-855d-43260fd18a55/jobs/1295/parallel-runs/0/steps/0-107) of this script running.
Any test instance using this [builder branch](https://github.com/greenpeace/planet4-test-umbriel/commit/ba41c5fce9331626b23732bd343f84c47f697f9d) and triggered with a commit prefixed with `[RESET]` should run it and be restored to defaultcontent.
=> Add script to reset test instance

src/bin/test_account_add.sh
This is needed in order for the test user to be able to change settings under the Planet 4 menu.
Example of [test failing](https://output.circle-artifacts.com/output/job/84e7cbbc-397f-4f72-b04f-0f935ef058d2/artifacts/0/usr/artifacts/playwright/report/index.html#?testId=ab27a62b87f2f41493f0-fbff68992012723ccf7b) because of limited permissions, when trying to set an Act page.
=> Change test user permissions to administrator

src/bin/test_account_add.sh
This is just a precaution to make sure this script is not accidentally used in a production website, if we start using this script in more pipelines.
=> Adjust test user creation to skip production sites.

src/bin/rewrite_app_repos.sh
Following https://github.com/greenpeace/planet4-master-theme/pull/2020#issuecomment-1740999201 
Add `--legacy-peer-deps` to avoid react [packages conflicts](https://app.circleci.com/pipelines/github/greenpeace/planet4-norway/2481/workflows/b1f85774-7d47-489f-a39d-1c64eefc6862/jobs/6241)
=> Fix npm command
